### ISSUE TITLE
Channel link is broken in Patchwork

### ISSUE THREAD

**Issue by clehner** [patchkit/patchkit-flat-msg-thread#1]
In the message heading, the channel link in "in #<channel>" links to `/channel/<channel>` instead of `#/channel/<channel>`, so clicking it results in a 404.

https://github.com/patchkit/patchkit-flat-msg-thread/blob/master/index.jsx#L366

Should this be changed to add the `#/`, or make the URL configurable through passing in some option?

**Comment by dangerousbeans** [comment]
Just ran into this too
